### ISSUE TITLE
Secure aggregation

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#12]
Setup secure aggregation

**Comment by ClementMayer** [comment]
Secure aggregation is a way to add in the model a mask at the level of each node, which disappears when the different models are aggregated to have the final model. 
This feature is more used in federated learning than in distributed learning. However, the use of secure aggregation can still make a lot of sense in model assembling. 
Functionalities are being developed in the framework of some projects. 
There will not be any immediate work on this feature.

**Comment by RomainGoussault** [comment]
Closing stale issue.
