### ISSUE TITLE
[FEATURE_REQUEST] Doc about the Compute Plan

### ISSUE THREAD

**Issue by celinejacques** [Substra/substra-documentation#133]
## Introduction

Hello! 
As a data scientist, I'm exploring the possibilities offered by Substra to train models. 
I would like to launch an example of federated learning orchestrated by a compute plan but I didn't find so much information in the readme and docs. So I don't totally understand how the compute plan works and how it can generate a federated learning experiment.  

## Describe the ideal feature

The generic explanation about the compute plan is clear and examples help to understand how a part of it can be implemented. Nevertheless, it would be worth to detail all options possible with a compute plan (transfer learning by stipulating with model to use for initialization, aggregation after each epoch, after each batch, etc.).

## Is there any already existing similar feature?

The example in the folder [Examples](https://github.com/SubstraFoundation/substra/tree/master/examples/compute_plan) of the repo Substra is useful to understand some subtilities but it only uses Transfer Learning without aggregation step.

**Comment by RomainGoussault** [comment]
Now in the documentation! https://docs.substra.org/
