### ISSUE TITLE
Integrate PET (Privacy Enhancing Technologies) in Substra

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#15]
Integrate PET (Privacy Enhancing Technologies) in Substra

**Comment by ClementMayer** [comment]
The idea is to present cases of use of PET implementation within the framework of Substra. This could take the form of a blog article to explain how this was done. 
A first experiment could be done with PYSYFT or TensorFlow Privacy.
The next step is to estimate the time needed to study the subject to see if it can be studied quickly.

**Comment by lcchua** [comment]
Yes this will be great. In line with others like Xain, Openmined. I hope this can be a priority one in your roadmap.

**Comment by bowni** [comment]
Could we link here the example Fabien worked on with PyDP? @natct10 @ClementMayer

**Comment by ClementMayer** [comment]
The document is [here](https://docs.google.com/document/d/1zUjDB-LBVIWXD3j91ErU1Oqfmt4bhgHcJy6bTUvcH58/edit#heading=h.zbat5zqiyyne)

**Comment by natct10** [comment]
> Could we link here the example Fabien worked on with PyDP? @natct10 @ClementMayer

It would be absolutely awesome, indeed, but it needs to be reviewed!
You can have a look [here](https://github.com/SubstraFoundation/substra-examples/pull/3)

**Comment by ClementMayer** [comment]
Update from last MAP committee (10/09/2020):

- A first example of differential privacy combined with Substra has been developed by Fabien Gelus (former intern at Substra Foundation):  

  - Exploration of tools for differential privacy by Fabien Gelus (before Opacus release by FB)
  - Use case of DP on Substra done by Fabien (with tensorflow-privacy)
- This  first example is a great step to demonstrate that is it possible to use DP libraries like tensorflow-privacy in ML configurations using Substra Framework 
- [Eric] Another tool can be explored as a use case: Opacus by Facebook, released recently, seems to have the ambition to become a new standard
- It would be also interesting to try with a “real” use case with Substra and DP, and not only on MNIST → use case to be identified. For example, Google used Differential Privacy to monitor people mobility during  COVID-19 crisis.
- [Amine] See this list of resources on DP.
- [Mathieu] Could this privacy be measured from a budget point of view? 
  - [Amine] Some interesting resources have been raised: Automatic Discovery of Privacy-Utility Pareto Fronts

**Comment by RomainGoussault** [comment]
Closing stale issue.
