### ISSUE TITLE
Connect to partner	

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#17]
Setup feature connect to partner.

**Comment by ClementMayer** [comment]
Motivation
Hopefully, a lot of people are going to install Substra Framework on their own infra. But for an ML-driven organization, building a (large, open-upon-invitation) network of data partners will be much more difficult. Yet, to promote the adoption of Substra, the quality and extent of the networks are key; Substra growth will be network based. Thus, Substra Foundation should help connect to existing partners’ network.

Proposition
In the frontend of Substra Framework (designed for data managers), we include an easy to access call-to-action (i.e. button or drop down menu) which helps “connect to partner network”. For instance, it could be “connect to PArtner Loop”. This CTA would connect to the certification authority of the partner network and formulate a clear request to the partner to integrate the node in their network. This request would both cover:

- a formal human-readable application to be examined by the partner
- an automated protocol setup to include the node in the network (provided the partner accepts the application).

Ideally, when the request is accepted the node auto-magically integrates the partner network (let’s say with minimal network / firewall configurations on the joining partner side). With this pattern Substra Framework can speed up the growth of our partners networks.

--

Although this feature is very interesting, it is still too early to imagine its development, which requires a critical number of organizations using the framework.

**Comment by ClementMayer** [comment]
Update from last MAP committee (10/09/2020):
- [Eric] It’s enthralling and fun, but quite far away! We still are in an R&D, PoCs, first usages phase. This idea of feature is more for the long-term horizon of a steady growth of usage

**Comment by RomainGoussault** [comment]
Closing stale issue.
