### ISSUE TITLE
Pre-processing of data through Substra

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#3]
Give the possibility to pre-process data through Substra

**Comment by ClementMayer** [comment]
The pre-processing of data is a time-consuming job. It could be interesting to be able, in the Substra framework, to perform data pre-processing work and to store intermediate data. 
However, this raises security issues in relation to this storage of intermediate data. 
Data pre-processing is a subject to have in mind but it will not be addressed in the immediate future.

**Comment by RomainGoussault** [comment]
Closing stale issue.
