### ISSUE TITLE
[Typos]

### ISSUE THREAD

**Issue by DanieleCremoniniOwkin** [Substra/substra-documentation#337]
## Describe the bug

This https://docs.substra.org/en/stable/substrafl_doc/substrafl_overview.html documentation page states:

> Full support on the following OS:
> Ubuntu 22.06

This should be instead:

> Full support of the following OS:
> Ubuntu 22.04

**Comment by SdgJlbl** [comment]
Hello, thanks for the report. 
Feel free to open a PR for typo fixes next time if you have the inclination :)
