### ISSUE TITLE
Set up a testnet of Substra

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#4]
Set up a testnet of Substra

**Comment by ClementMayer** [comment]
An installation of a Substra instance in the cloud is in progress. It is already running but work is in progress to make it accessible. 
A presentation and a communication will take place soon on the subject.

**Comment by ClementMayer** [comment]
Update from last MAP committee (10/09/2020):


- [Nathanaël, Chris] We succeeded today in a local setup with a very clear documentation. A setup on a node with two organizations on a virtual machine has also been done and can be made available upon request.
- [Mathieu] It would be super interesting to have a few examples easily executables on a publicly accessible instance (e.g. OVH). Budget might be a topic though
  - [Eric] Budget could be covered by OVH sponsorship
  - [Chris] In such a setup couldn’t there be a problem of resource accumulation?.
  - [Camille] It can be handled with some simple hacks to launch several learning tasks on Titanic for exemple (adding a random part on the algo script, etc.) 
- → The next step is to install a test instance on OVH in order to allow a Data Scientist to play with Substra without having to perform a deploy
- [Amine] Possibility to package the VM on OVH or AWS marketplaces? 
  - Nathanaël and Eric will look into that

**Comment by RomainGoussault** [comment]
Closing stale issue.
