### ISSUE TITLE
Use glossary directive

### ISSUE THREAD

**Issue by jmorel** [Substra/substra-documentation#46]
Our current glossary is a markdown page that manually creates titles and table of contents.

We should convert it to RST and use the glossary directive instead: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary

On top of better formatting, this makes all glossary terms global references in our documentation which makes linking to them very easy.

**Comment by natct10** [comment]
Absolutely, thank you @jmorel !!
