### ISSUE TITLE
Filter out / remove assets on the front

### ISSUE THREAD

**Issue by RomainGoussault** [Substra/substra-documentation#49]
When you have registered an asset (dataset or objective for instance) that has bug a in it, it would to be nice to be able to remove it from the front. I know we can not delete it but move it to "trash" somehow would be good.

I fear that after experimentation with Substra, my front page will be filled with datasets and objectives that do not work properly !

I know there is a filter option but it will be nice to automatically filter the 'trash' assets.

**Comment by ClementMayer** [comment]
Total deletion of a dataset is not possible for reasons of traceability and reproducibility. But it is possible to imagine, for example, an additional step in the validation input of a dataset to avoid keeping too many dataset in error. 
Setting up a workgroup to work on this issue and identify a solution.

**Comment by RomainGoussault** [comment]
Filter are now implemented in the python lib and web interface
