### ISSUE TITLE
Advanced permission

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#6]
Regime that covers serial and parallel learning - empowering the data controller - technique and concept - data governance platform

**Comment by ClementMayer** [comment]
It is already possible to set up different rights on assets in Substra, but a redesign is necessary to integrate finer cases adapted to all use cases of the framework.
For example, here are some examples: 
- All the models trained on a dataset that I made accessible are accessible to me.
- All the models created from an algorithm I provided are accessible to me
- and so on.
An in-depth reflection must be initiated to think about these different regimes and how to set them up. 
A working group will be organized to reflect on this subject.

**Comment by SaboniAmine** [comment]
Maybe the [Biscuit](https://github.com/CleverCloud/biscuit) framework could be the tool that lets you declare permissions per users/roles, in a distributed mode.

**Comment by ClementMayer** [comment]
Update from last MAP committee (10/09/2020):

- [Chris, Céline] Are there ongoing developments on that aspect? What concepts or approaches of permissions are considered?
- [Amine] An idea: we could imagine permissions (e.g. granted by dataset providers to data scientist) conditional to a privacy budget (differential privacy epsilon)
- [Camille] There is no new development at this stage. Owkin will work on it probably on Q4.

**Comment by RomainGoussault** [comment]
Closing stale issue.
