### ISSUE TITLE
Data preview

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-documentation#7]
Allow a user to have a preview of data on several samples.

**Comment by ClementMayer** [comment]
The objective would be to give access to a starting kit, a small percentage of data (10%) highly anonymized that would allow a data scientist to have material to prepare his algos and models. Reflections have started on the subject but have not yet been implemented. It would be a question of having an "additional" data set in addition to the train and test data.

**Comment by RomainGoussault** [comment]
Closing stale issue.
