### ISSUE TITLE
[BUG] ':+1::tada:' is not rendered on the Contributing page of the doc

### ISSUE THREAD

**Issue by bowni** [Substra/substra-documentation#81]
## Describe the bug

':+1::tada:' is not rendered on the Contributing page of the doc

## How To Reproduce

1. Open the [Contributing page of the doc](https://doc.substra.ai/contribute/CONTRIBUTING.html) in your browser
2. Check out the first line after the article title

## Expected behavior

Shouldn't it render an emoji or something like that?

**Comment by RomainGoussault** [comment]
Closing stale issue.
