### ISSUE TITLE
[BUG] Quotes/Notes are not rendered on the doc website

### ISSUE THREAD

**Issue by bowni** [Substra/substra-documentation#82]
## Describe the bug

Quotes/Notes written in `.md` sources with `> ...` are not rendered properly on the documentation website.

## How To Reproduce

1. Go to [this page](https://doc.substra.ai/getting_started/installation/local_install_skaffold.html#need_help) and check out the first line after the article title

## Expected behavior

Depending on the rendering template, his should render something like a vertical bar, maybe a different text color.

**Comment by natct10** [comment]
Okay, thank you @bowni, I will look into this!

**Comment by natct10** [comment]
> Okay, thank you @bowni, I will look into this!

This quote/note element is only rendered with a bigger margin.

**Comment by RomainGoussault** [comment]
Closing stale issue.
