### ISSUE TITLE
Add hlf charts configs

### ISSUE THREAD

**Issue by natct10** [Substra/substra-documentation#96]
- [ ] Introduce structure and some relevant items
- [ ] add ref to [hlf charts readme](https://github.com/SubstraFoundation/hlf-k8s/tree/master/charts/hlf-k8s#configuration)
- [ ] Add [add orga to system channel](https://github.com/SubstraFoundation/hlf-k8s/tree/master/charts/hlf-k8s#add-an-organization-to-the-system-channel)

**Comment by RomainGoussault** [comment]
Now in the documentation: https://docs.substra.org/
